project:
  type: website

website:
  title: "Jess Graves"
  navbar:
    left:
      # - href: index.qmd
      #   text: Home
      # - href: index.qmd
        # text: About
      - href: posts.qmd
        text: Posts
      - href: publications.qmd
        text: Publications

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

filters:
  - _filters/limit-authors.lua
  
execute: 
  freeze: auto